%% D20/Core43: influence of return-leg glue-line thickness on Lm
% Assumption:
%   - upper and lower centre posts are each ground by 0.1 mm;
%   - total centre-post grind is therefore dTotal = 0.2 mm;
%   - gGlue is adhesive trapped BETWEEN the return-leg mating faces;
%   - the assembled centre gap is dTotal + gGlue.
%
% If adhesive is only an external side fillet and the return faces remain
% in direct contact, its physical bead/fillet thickness is not a magnetic
% gap.  In that case use gGlue = 0 in this calculation.

clear; clc; close all;

mu0 = 4*pi*1e-7;
Np = 36;
LmTarget_H = 2.3e-3;

% Current D20/Core43 magnetic areas.
Ac_m2 = 314.159265358979e-6;
Ar_m2 = 252.896559303128e-6;

% The present AEDT/MATLAB reference uses one uniform 0.093512 mm split
% between both core halves.  Infer the unchanged ferrite reluctance from
% that calibrated 2.3 mH reference, then replace its gap configuration by
% a centre-ground plus return-leg glue-gap configuration.
gUniformRef_m = 0.0935123206677404e-3;
Rtarget_AtPerWb = Np^2/LmTarget_H;
RgapRef_AtPerWb = gUniformRef_m/mu0*(1/Ac_m2 + 1/Ar_m2);
Rcore_AtPerWb = Rtarget_AtPerWb - RgapRef_AtPerWb;

grindEachCore_mm = 0.1;
dTotal_m = 2*grindEachCore_mm*1e-3;
grindEachCore07_mm = 0.07;
dTotal07_m = 2*grindEachCore07_mm*1e-3;

gGlue_um = (0:1:100)';
gGlue_m = gGlue_um*1e-6;
gCentre_m = dTotal_m + gGlue_m;
areaRatio = Ac_m2/Ar_m2;
% Centre-referred equivalent gap.  A return-leg gap is weighted by
% Ac/Ar because the return cross-section differs from the centre post.
gEquivalentCentre_m = gCentre_m + areaRatio*gGlue_m;

RcentreGap = gCentre_m./(mu0*Ac_m2);
RreturnGap = gGlue_m./(mu0*Ar_m2);
Rtotal = Rcore_AtPerWb + RcentreGap + RreturnGap;
Lm_H = Np^2./Rtotal;
AL_nH_per_turn2 = Lm_H/Np^2*1e9;
deltaLm_pct = 100*(Lm_H/LmTarget_H - 1);
within5pct = abs(deltaLm_pct)<=5;

% Second production option: grind 0.07 mm from each centre-post half,
% giving 0.14 mm total centre recess before assembly.
gCentre07_m = dTotal07_m + gGlue_m;
gEquivalentCentre07_m = gCentre07_m + areaRatio*gGlue_m;
Rtotal07 = Rcore_AtPerWb + gCentre07_m./(mu0*Ac_m2) + ...
    gGlue_m./(mu0*Ar_m2);
Lm07_H = Np^2./Rtotal07;
AL07_nH_per_turn2 = Lm07_H/Np^2*1e9;
deltaLm07_pct = 100*(Lm07_H/LmTarget_H-1);
within5pct07 = abs(deltaLm07_pct)<=5;

Result = table(gGlue_um,gCentre_m*1e3,gEquivalentCentre_m*1e3, ...
    Lm_H*1e3,AL_nH_per_turn2,deltaLm_pct,within5pct, ...
    'VariableNames',{'ReturnGlueGap_um','ActualCentreGap_mm', ...
    'CentreReferredEquivalentGap_mm','Lm_mH','AL_nH_per_turn2', ...
    'DeltaFrom2p3mH_pct','Within5pct'});
Result07 = table(gGlue_um,gCentre07_m*1e3,gEquivalentCentre07_m*1e3, ...
    Lm07_H*1e3,AL07_nH_per_turn2,deltaLm07_pct,within5pct07, ...
    'VariableNames',{'ReturnGlueGap_um','ActualCentreGap_mm', ...
    'CentreReferredEquivalentGap_mm','Lm_mH','AL_nH_per_turn2', ...
    'DeltaFrom2p3mH_pct','Within5pct'});

% Glue gap that would reproduce exactly 2.3 mH with 0.1 mm ground from
% each centre-post half.
gapCoefficient = 1/(mu0*Ac_m2) + 1/(mu0*Ar_m2);
gGlueForTarget_m = (Rtarget_AtPerWb - Rcore_AtPerWb - ...
    dTotal_m/(mu0*Ac_m2))/gapCoefficient;
gGlueAtMinus5pct_m = (Np^2/(0.95*LmTarget_H) - Rcore_AtPerWb - ...
    dTotal_m/(mu0*Ac_m2))/gapCoefficient;
gGlueAtPlus5pct_m = (Np^2/(1.05*LmTarget_H) - Rcore_AtPerWb - ...
    dTotal_m/(mu0*Ac_m2))/gapCoefficient;
allowableGlueMin_m = max(0,gGlueAtPlus5pct_m);
allowableGlueMax_m = max(0,gGlueAtMinus5pct_m);

gGlueForTarget07_m = (Rtarget_AtPerWb - Rcore_AtPerWb - ...
    dTotal07_m/(mu0*Ac_m2))/gapCoefficient;
gGlue07AtMinus5pct_m = (Np^2/(0.95*LmTarget_H) - Rcore_AtPerWb - ...
    dTotal07_m/(mu0*Ac_m2))/gapCoefficient;
gGlue07AtPlus5pct_m = (Np^2/(1.05*LmTarget_H) - Rcore_AtPerWb - ...
    dTotal07_m/(mu0*Ac_m2))/gapCoefficient;
allowableGlue07Min_m = max(0,gGlue07AtPlus5pct_m);
allowableGlue07Max_m = max(0,gGlue07AtMinus5pct_m);

% Explicit production cases.  External side fillet thickness is listed as
% NaN because it can be mechanically thick but creates zero magnetic gap
% when it stays off the horizontal mating faces.
caseName = ["External side fillet";"Return-face glue: exact target"; ...
    "Return-face glue: 5 um";"Return-face glue: 10 um"; ...
    "Return-face glue: 20 um";"Return-face glue: 50 um"; ...
    "Glass beads: 90 um";"Glass beads: 100 um"];
physicalAdhesive_um = [NaN;gGlueForTarget_m*1e6;5;10;20;50;90;100];
magneticReturnGap_um = [0;gGlueForTarget_m*1e6;5;10;20;50;90;100];
caseReturnGap_m = magneticReturnGap_um*1e-6;
caseCentreGap_m = dTotal_m + caseReturnGap_m;
caseEquivalentGap_m = caseCentreGap_m + areaRatio*caseReturnGap_m;
caseReluctance = Rcore_AtPerWb + caseCentreGap_m/(mu0*Ac_m2) + ...
    caseReturnGap_m/(mu0*Ar_m2);
caseLm_H = Np^2./caseReluctance;
caseAL = caseLm_H/Np^2*1e9;
caseDelta = 100*(caseLm_H/LmTarget_H-1);
ProductionCases = table(caseName,physicalAdhesive_um,magneticReturnGap_um, ...
    caseCentreGap_m*1e3,caseEquivalentGap_m*1e3,caseLm_H*1e3,caseAL,caseDelta, ...
    'VariableNames',{'Scenario','PhysicalAdhesiveThickness_um', ...
    'MagneticReturnGap_um','ActualCentreGap_mm', ...
    'CentreReferredEquivalentGap_mm','Lm_mH','AL_nH_per_turn2', ...
    'DeltaFrom2p3mH_pct'});

caseName07 = ["0.07 mm/core: external side fillet"; ...
    "0.07 mm/core: exact target";"0.07 mm/core: 20 um return gap"; ...
    "0.07 mm/core: 30 um return gap";"0.07 mm/core: 40 um return gap"; ...
    "0.07 mm/core: 50 um return gap";"0.07 mm/core: 90 um beads"; ...
    "0.07 mm/core: 100 um beads"];
caseReturnGap07_um = [0;gGlueForTarget07_m*1e6;20;30;40;50;90;100];
caseReturnGap07_m = caseReturnGap07_um*1e-6;
caseCentreGap07_m = dTotal07_m + caseReturnGap07_m;
caseEquivalentGap07_m = caseCentreGap07_m + areaRatio*caseReturnGap07_m;
caseReluctance07 = Rcore_AtPerWb + caseCentreGap07_m/(mu0*Ac_m2) + ...
    caseReturnGap07_m/(mu0*Ar_m2);
caseLm07_H = Np^2./caseReluctance07;
ProductionCases07 = table(caseName07,caseReturnGap07_um, ...
    caseCentreGap07_m*1e3,caseEquivalentGap07_m*1e3,caseLm07_H*1e3, ...
    caseLm07_H/Np^2*1e9,100*(caseLm07_H/LmTarget_H-1), ...
    'VariableNames',{'Scenario','MagneticReturnGap_um','ActualCentreGap_mm', ...
    'CentreReferredEquivalentGap_mm','Lm_mH','AL_nH_per_turn2', ...
    'DeltaFrom2p3mH_pct'});

%% Grind-depth family: glue gap versus Lm for several per-core grinds
% Same model as above, repeated for every per-core grind depth in
% grindFamily_mm.  Each row of LmFamily_H is one glue thickness, each
% column one grind depth.
grindFamily_mm = [0.06 0.07 0.08 0.09 0.10];
nGrind = numel(grindFamily_mm);
dTotalFamily_m = 2*grindFamily_mm*1e-3;
LmFamily_H = zeros(numel(gGlue_um),nGrind);
for j = 1:nGrind
    LmFamily_H(:,j) = Np^2./(Rcore_AtPerWb + ...
        (dTotalFamily_m(j) + gGlue_m)./(mu0*Ac_m2) + gGlue_m./(mu0*Ar_m2));
end

% Closed-form glue gap for exact target and for the +/-5% limits.  A
% negative value means the grind alone already gives less than that Lm, so
% no amount of glue can reach it; those limits are clamped to zero.
glueAt_m = @(LmGoal_H) (Np^2./LmGoal_H - Rcore_AtPerWb - ...
    dTotalFamily_m/(mu0*Ac_m2))/gapCoefficient;
glueTargetFamily_m = glueAt_m(LmTarget_H);
glueMinFamily_m = max(0,glueAt_m(1.05*LmTarget_H));
glueMaxFamily_m = glueAt_m(0.95*LmTarget_H);
targetReachable = glueTargetFamily_m >= 0;
windowExists = glueMaxFamily_m >= 0;
glueMaxFamily_m = max(0,glueMaxFamily_m);

LmNoGlueFamily_H = LmFamily_H(1,:);

% Spot check at a specified cured glue thickness between the return faces.
glueCheck_um = 30;
LmGlueCheckFamily_H = Np^2./(Rcore_AtPerWb + ...
    (dTotalFamily_m + glueCheck_um*1e-6)/(mu0*Ac_m2) + ...
    glueCheck_um*1e-6/(mu0*Ar_m2));
deltaGlueCheckFamily_pct = 100*(LmGlueCheckFamily_H/LmTarget_H-1);

GrindFamilySummary = table(grindFamily_mm',dTotalFamily_m'*1e3, ...
    LmNoGlueFamily_H'*1e3,100*(LmNoGlueFamily_H'/LmTarget_H-1), ...
    LmGlueCheckFamily_H'*1e3,deltaGlueCheckFamily_pct', ...
    abs(deltaGlueCheckFamily_pct')<=5, ...
    glueTargetFamily_m'*1e6,targetReachable', ...
    glueMinFamily_m'*1e6,glueMaxFamily_m'*1e6, ...
    (glueMaxFamily_m'-glueMinFamily_m')*1e6.*windowExists', ...
    'VariableNames',{'GrindPerCore_mm','TotalCentreGrind_mm', ...
    'LmNoGlue_mH','DeltaNoGlue_pct', ...
    sprintf('LmAt%gumGlue_mH',glueCheck_um), ...
    sprintf('DeltaAt%gumGlue_pct',glueCheck_um), ...
    sprintf('Within5pctAt%gumGlue',glueCheck_um), ...
    'GlueForTarget_um','TargetReachable', ...
    'GlueMinFor5pct_um','GlueMaxFor5pct_um','GlueWindowWidth_um'});

familyVarNames = [{'ReturnGlueGap_um'}, ...
    compose('Lm_grind%03.0fum_mH',grindFamily_mm*1e3)];
GrindFamilyLm = array2table([gGlue_um LmFamily_H*1e3], ...
    'VariableNames',familyVarNames);

%% Required centre-post grinding versus residual return-leg gap
% For a selected residual gap at the return faces, solve the total centre
% recess dTotalRequired that retains Lm=2.3 mH.  The assembled centre gap
% is dTotalRequired + gReturnResidual.  If both halves are ground equally,
% each core receives half of dTotalRequired.
gReturnResidual_um = (0:1:100)';
gReturnResidual_m = gReturnResidual_um*1e-6;
centreOnlyEquivalentGap_m = mu0*Ac_m2*(Rtarget_AtPerWb-Rcore_AtPerWb);
dTotalRequired_m = centreOnlyEquivalentGap_m - ...
    (1+areaRatio)*gReturnResidual_m;
gCentreAssembledRequired_m = dTotalRequired_m + gReturnResidual_m;
grindEachRequired_m = dTotalRequired_m/2;
grindingIsPhysical = dTotalRequired_m>=0;

RequiredGrind = table(gReturnResidual_um,dTotalRequired_m*1e3, ...
    grindEachRequired_m*1e3,gCentreAssembledRequired_m*1e3, ...
    grindingIsPhysical, ...
    'VariableNames',{'ReturnLegResidualGap_um','RequiredTotalCentreGrind_mm', ...
    'RequiredGrindPerCore_mm','AssembledCentreGap_mm','NonnegativeGrind'});

selectedResidual_um = [0 2 5 10 20 30 40 50 75 90 93 94 100]';
RequiredGrindSelected = RequiredGrind( ...
    ismember(RequiredGrind.ReturnLegResidualGap_um,selectedResidual_um),:);
returnGapForZeroGrind_m = centreOnlyEquivalentGap_m/(1+areaRatio);

%% Bead-controlled uniform gap with no centre-post grinding
% If the gap is set purely by glass beads dispersed in the adhesive and the
% centre post is left unground, every mating face opens by the same bead
% diameter.  The flux then crosses that gap twice per loop, once at the
% centre post and once at the return legs, so the centre-referred gap is
% (1 + Ac/Ar) times the bead diameter.
beadDia_um = (60:1:130)';
beadDia_m = beadDia_um*1e-6;
RbeadTotal = Rcore_AtPerWb + beadDia_m./(mu0*Ac_m2) + beadDia_m./(mu0*Ar_m2);
LmBead_H = Np^2./RbeadTotal;
beadEquivalentGap_m = (1+areaRatio)*beadDia_m;
deltaBead_pct = 100*(LmBead_H/LmTarget_H - 1);

% Bead diameter that lands exactly on target.  This must reproduce the
% uniform split gap the reference was calibrated at, because an unground
% core with a uniform spacer IS that reference configuration.
beadForTarget_m = returnGapForZeroGrind_m;

% Per-micron sensitivity of the two processes, as %Lm per um of thickness
% error at the target operating point.  The bead route is penalised twice:
% the gap appears at both the centre and the return faces, and the return
% cross-section is smaller so each micron there costs more reluctance.
RperMicronBead = 1e-6*(1/(mu0*Ac_m2) + 1/(mu0*Ar_m2));
RperMicronGrind = 1e-6/(mu0*Ac_m2);
sensBead_pctPerUm = 100*RperMicronBead/Rtarget_AtPerWb;
sensGrind_pctPerUm = 100*RperMicronGrind/Rtarget_AtPerWb;
sensRatio = sensBead_pctPerUm/sensGrind_pctPerUm;

% Bead diameter window that still keeps Lm inside +/-5%.
beadGapCoefficient = 1/(mu0*Ac_m2) + 1/(mu0*Ar_m2);
beadAtMinus5_m = (Np^2/(0.95*LmTarget_H)-Rcore_AtPerWb)/beadGapCoefficient;
beadAtPlus5_m = (Np^2/(1.05*LmTarget_H)-Rcore_AtPerWb)/beadGapCoefficient;
beadWindowFor5pct_um = [beadAtPlus5_m beadAtMinus5_m]*1e6;

% Nominal 0.1 mm beads, the size under consideration.
Lm100umBead_H = Np^2/(Rcore_AtPerWb + 1e-4/(mu0*Ac_m2) + 1e-4/(mu0*Ar_m2));
delta100umBead_pct = 100*(Lm100umBead_H/LmTarget_H-1);
% Turns that would bring 0.1 mm beads back onto target, since Lm scales N^2.
NpFor100umBead = Np*sqrt(LmTarget_H/Lm100umBead_H);

BeadSweep = table(beadDia_um,beadEquivalentGap_m*1e3,LmBead_H*1e3, ...
    LmBead_H/Np^2*1e9,deltaBead_pct,abs(deltaBead_pct)<=5, ...
    'VariableNames',{'BeadDiameter_um','CentreReferredEquivalentGap_mm', ...
    'Lm_mH','AL_nH_per_turn2','DeltaFrom2p3mH_pct','Within5pct'});

%% Ferrite permeability tolerance on mu_i
% The ferrite reluctance inferred above corresponds to the nominal
% datasheet permeability.  Because Rcore = le/(mu0*mur*Ae), a relative
% permeability factor kMu simply scales it as Rcore/kMu.  The gap
% reluctance is unaffected, so the sensitivity of Lm is set by how much of
% the total reluctance the ferrite still owns.
muTolerance_pct = 30;
sampleGlue_um = [0 2 5 10 20 30 40 50 75 100]';
muFactor = [1-muTolerance_pct/100, 1, 1+muTolerance_pct/100];
muLabel = [sprintf("mu -%g%%",muTolerance_pct),"mu nominal", ...
    sprintf("mu +%g%%",muTolerance_pct)];
RcoreMu_AtPerWb = Rcore_AtPerWb./muFactor;

% Fraction of the total reluctance contributed by the ferrite at nominal
% permeability.  This is the figure of merit: Lm sensitivity to mu is
% roughly this fraction times the mu error.
coreFractionNominal = Rcore_AtPerWb./Rtotal;
coreFractionNominal07 = Rcore_AtPerWb./Rtotal07;

% Sweep both grind options against the glue gap for each permeability.
LmMu_H = zeros(numel(gGlue_um),numel(muFactor));
LmMu07_H = zeros(numel(gGlue_um),numel(muFactor));
for j = 1:numel(muFactor)
    LmMu_H(:,j) = Np^2./(RcoreMu_AtPerWb(j) + RcentreGap + RreturnGap);
    LmMu07_H(:,j) = Np^2./(RcoreMu_AtPerWb(j) + ...
        gCentre07_m./(mu0*Ac_m2) + gGlue_m./(mu0*Ar_m2));
end
LmMuLow_H = LmMu_H(:,1);  LmMuNom_H = LmMu_H(:,2);  LmMuHigh_H = LmMu_H(:,3);
LmMuLow07_H = LmMu07_H(:,1); LmMuNom07_H = LmMu07_H(:,2); LmMuHigh07_H = LmMu07_H(:,3);

% Deviation of each permeability corner from the nominal-mu curve at the
% same glue gap, and the total peak-to-peak band.
deltaMuLow_pct = 100*(LmMuLow_H./LmMuNom_H - 1);
deltaMuHigh_pct = 100*(LmMuHigh_H./LmMuNom_H - 1);
muBand_pct = deltaMuHigh_pct - deltaMuLow_pct;
deltaMuLow07_pct = 100*(LmMuLow07_H./LmMuNom07_H - 1);
deltaMuHigh07_pct = 100*(LmMuHigh07_H./LmMuNom07_H - 1);
muBand07_pct = deltaMuHigh07_pct - deltaMuLow07_pct;

% Column names carry the tolerance actually used so the exported CSV files
% stay self-describing when muTolerance_pct is changed.
muVarNames = {'ReturnGlueGap_um','CoreReluctanceShare_pct', ...
    sprintf('Lm_muMinus%g_mH',muTolerance_pct),'Lm_muNominal_mH', ...
    sprintf('Lm_muPlus%g_mH',muTolerance_pct), ...
    sprintf('DeltaAtMuMinus%g_pct',muTolerance_pct), ...
    sprintf('DeltaAtMuPlus%g_pct',muTolerance_pct),'PeakToPeakBand_pct'};
MuSensitivity = table(gGlue_um,100*coreFractionNominal, ...
    LmMuLow_H*1e3,LmMuNom_H*1e3,LmMuHigh_H*1e3, ...
    deltaMuLow_pct,deltaMuHigh_pct,muBand_pct, ...
    'VariableNames',muVarNames);
MuSensitivity07 = table(gGlue_um,100*coreFractionNominal07, ...
    LmMuLow07_H*1e3,LmMuNom07_H*1e3,LmMuHigh07_H*1e3, ...
    deltaMuLow07_pct,deltaMuHigh07_pct,muBand07_pct, ...
    'VariableNames',muVarNames);
MuSensitivitySelected = MuSensitivity( ...
    ismember(MuSensitivity.ReturnGlueGap_um,sampleGlue_um),:);
MuSensitivitySelected07 = MuSensitivity07( ...
    ismember(MuSensitivity07.ReturnGlueGap_um,sampleGlue_um),:);

% Reference point for comparison: the ungapped core, where the ferrite owns
% the entire reluctance and Lm tracks mu one for one.
LmUngappedMu_mH = Np^2./RcoreMu_AtPerWb*1e3;

% Same permeability corners applied to the unground bead-controlled build at
% its on-target bead diameter, for a like-for-like comparison with grinding.
LmBeadMu_mH = Np^2./(RcoreMu_AtPerWb + beadForTarget_m*beadGapCoefficient)*1e3;
deltaBeadMu_pct = 100*(LmBeadMu_mH/(Np^2/ ...
    (Rcore_AtPerWb + beadForTarget_m*beadGapCoefficient)*1e3) - 1);

% Worst-case stack-up at the nominal design point (glue gap = 0, i.e. the
% external side fillet process).  The mu corner and the grind-depth
% tolerance are independent, so they are combined multiplicatively on
% reluctance rather than added as percentages of Lm.
grindTolerance_mm = 0.02;
grindCorner_m = dTotal_m + [grindTolerance_mm 0 -grindTolerance_mm]*1e-3;
[muGrid,grindGrid] = ndgrid(muFactor,grindCorner_m);
LmCorner_H = Np^2./(Rcore_AtPerWb./muGrid + grindGrid./(mu0*Ac_m2));
LmCornerMin_mH = min(LmCorner_H(:))*1e3;
LmCornerMax_mH = max(LmCorner_H(:))*1e3;
LmNominalNoGlue_mH = Np^2/(Rcore_AtPerWb + dTotal_m/(mu0*Ac_m2))*1e3;
cornerSpreadLow_pct = 100*(LmCornerMin_mH/LmNominalNoGlue_mH - 1);
cornerSpreadHigh_pct = 100*(LmCornerMax_mH/LmNominalNoGlue_mH - 1);

CornerCases = table( ...
    repmat(muLabel(:),numel(grindCorner_m),1), ...
    reshape(grindGrid,[],1)*1e3, ...
    reshape(LmCorner_H,[],1)*1e3, ...
    100*(reshape(LmCorner_H,[],1)/LmTarget_H-1), ...
    'VariableNames',{'PermeabilityCorner','TotalCentreGap_mm','Lm_mH', ...
    'DeltaFrom2p3mH_pct'});

outDir = fullfile(fileparts(mfilename('fullpath')),'output','36_3_2_pot', ...
    'D20_Core43','glue_gap_sweep');
if ~exist(outDir,'dir'), mkdir(outDir); end
writetable(Result,fullfile(outDir,'D20_0p1mm_each_core_glue_gap_Lm_sweep.csv'));
writetable(Result07,fullfile(outDir,'D20_0p07mm_each_core_glue_gap_Lm_sweep.csv'));
writetable(ProductionCases,fullfile(outDir,'D20_0p1mm_each_core_production_cases.csv'));
writetable(ProductionCases07,fullfile(outDir,'D20_0p07mm_each_core_production_cases.csv'));
writetable(RequiredGrind,fullfile(outDir, ...
    'D20_return_gap_required_centre_grind_for_2p3mH.csv'));
writetable(RequiredGrindSelected,fullfile(outDir, ...
    'D20_return_gap_required_centre_grind_selected.csv'));
writetable(MuSensitivity,fullfile(outDir, ...
    'D20_0p1mm_each_core_mu_tolerance_Lm_sweep.csv'));
writetable(MuSensitivity07,fullfile(outDir, ...
    'D20_0p07mm_each_core_mu_tolerance_Lm_sweep.csv'));
writetable(MuSensitivitySelected,fullfile(outDir, ...
    'D20_0p1mm_each_core_mu_tolerance_selected.csv'));
writetable(MuSensitivitySelected07,fullfile(outDir, ...
    'D20_0p07mm_each_core_mu_tolerance_selected.csv'));
writetable(CornerCases,fullfile(outDir, ...
    'D20_mu_and_grind_corner_cases.csv'));
writetable(BeadSweep,fullfile(outDir, ...
    'D20_no_grind_bead_controlled_gap_sweep.csv'));
writetable(GrindFamilySummary,fullfile(outDir, ...
    'D20_grind_family_glue_gap_summary.csv'));
writetable(GrindFamilyLm,fullfile(outDir, ...
    'D20_grind_family_glue_gap_Lm_sweep.csv'));

fig = figure('Color','w','Position',[100 100 1040 660]);
ax = axes(fig); hold(ax,'on'); grid(ax,'on'); box(ax,'on');
% Grind depth is an ordered quantity, so the curves use one sequential
% ramp: light orange for the shallowest grind through deep blue for the
% deepest.
familyColors = [0.93 0.55 0.10; 0.86 0.24 0.08; 0.62 0.18 0.45; ...
    0.28 0.30 0.70; 0.04 0.32 0.75];
patch(ax,[0 100 100 0],[0.95 0.95 1.05 1.05]*LmTarget_H*1e3, ...
    [0.20 0.60 0.30],'FaceAlpha',0.08,'EdgeColor','none', ...
    'HandleVisibility','off');
yline(ax,LmTarget_H*1e3,'--','目标2.3 mH','LineWidth',1.5, ...
    'LabelHorizontalAlignment','right','LabelVerticalAlignment','bottom', ...
    'HandleVisibility','off');
yline(ax,0.95*LmTarget_H*1e3,':','-5%限制','LineWidth',1.1, ...
    'LabelHorizontalAlignment','right','LabelVerticalAlignment','bottom', ...
    'HandleVisibility','off');
yline(ax,1.05*LmTarget_H*1e3,':','+5%限制','LineWidth',1.1, ...
    'LabelHorizontalAlignment','right','LabelVerticalAlignment','top', ...
    'HandleVisibility','off');
for j = 1:nGrind
    if targetReachable(j)
        legendText = sprintf('研磨%.2f mm/片：无胶%.3f mH，目标胶层%.1f um', ...
            grindFamily_mm(j),LmNoGlueFamily_H(j)*1e3,glueTargetFamily_m(j)*1e6);
    else
        legendText = sprintf('研磨%.2f mm/片：无胶%.3f mH，无法到达目标', ...
            grindFamily_mm(j),LmNoGlueFamily_H(j)*1e3);
    end
    legendText = sprintf('%s，%g um胶■%.3f mH (%+.1f%%)',legendText, ...
        glueCheck_um,LmGlueCheckFamily_H(j)*1e3,deltaGlueCheckFamily_pct(j));
    plot(ax,gGlue_um,LmFamily_H(:,j)*1e3,'LineWidth',2.4, ...
        'Color',familyColors(j,:),'DisplayName',legendText);
    % Target crossings are marked on the 2.3 mH line itself rather than
    % with vertical rules, which would crowd five labels into one strip.
    if targetReachable(j)
        plot(ax,glueTargetFamily_m(j)*1e6,LmTarget_H*1e3,'o', ...
            'MarkerSize',8,'LineWidth',1.8,'Color',familyColors(j,:), ...
            'MarkerFaceColor','w','HandleVisibility','off');
    end
    % Filled square at the glue spot-check thickness.  Its value goes in
    % the legend: on-plot labels here get crossed by the neighbouring curves.
    plot(ax,glueCheck_um,LmGlueCheckFamily_H(j)*1e3,'s','MarkerSize',8, ...
        'Color',familyColors(j,:),'MarkerFaceColor',familyColors(j,:), ...
        'HandleVisibility','off');
end
xline(ax,glueCheck_um,'-.',sprintf('胶层%g um',glueCheck_um), ...
    'LineWidth',1.2,'Color',[0.35 0.35 0.35], ...
    'LabelVerticalAlignment','bottom','LabelHorizontalAlignment','left', ...
    'FontName','Microsoft YaHei','HandleVisibility','off');
xlabel(ax,'Cured adhesive thickness between return-leg faces (um)');
ylabel(ax,'Magnetizing inductance L_m (mH)');
title(ax,{'D20/Core43，N_p=36：外侧leg胶层气隙对L_m的影响', ...
    sprintf('每片中心柱研磨%s mm对比', ...
    strjoin(compose('%.2f',grindFamily_mm),' / '))}, ...
    'FontName','Microsoft YaHei');
subtitle(ax,'磁路解析估算；外侧桥接胶对应g_{glue}=0', ...
    'FontName','Microsoft YaHei');
legend(ax,'Location','northeast','FontName','Microsoft YaHei');
exportgraphics(fig,fullfile(outDir,'D20_0p1mm_each_core_glue_gap_Lm_sweep.png'), ...
    'Resolution',240);
savefig(fig,fullfile(outDir,'D20_0p1mm_each_core_glue_gap_Lm_sweep.fig'));

figGrind = figure('Color','w','Position',[130 130 980 620]);
axGrind = axes(figGrind); hold(axGrind,'on'); grid(axGrind,'on'); box(axGrind,'on');
plot(axGrind,gReturnResidual_um,dTotalRequired_m*1e3,'LineWidth',2.5, ...
    'Color',[0.78 0.12 0.06],'DisplayName','中心柱总研磨深度');
plot(axGrind,gReturnResidual_um,grindEachRequired_m*1e3,'--','LineWidth',2.0, ...
    'Color',[0.10 0.42 0.72],'DisplayName','每片磁芯研磨深度（对称研磨）');
yline(axGrind,0,'k-','LineWidth',1.1,'HandleVisibility','off');
xline(axGrind,returnGapForZeroGrind_m*1e6,':', ...
    sprintf('Zero grind at %.2f um',returnGapForZeroGrind_m*1e6), ...
    'LineWidth',1.4,'LabelVerticalAlignment','middle','HandleVisibility','off');
xlabel(axGrind,'Residual gap at return-leg mating faces (um)');
ylabel(axGrind,'Required centre-post grinding depth (mm)');
title(axGrind,{'D20/Core43：保持L_m=2.3 mH所需的中心柱研磨深度', ...
    '同时考虑外侧leg残余气隙和装配后的中心气隙'}, ...
    'FontName','Microsoft YaHei');
legend(axGrind,'Location','northeast','FontName','Microsoft YaHei');
exportgraphics(figGrind,fullfile(outDir, ...
    'D20_return_gap_required_centre_grind_for_2p3mH.png'),'Resolution',240);
savefig(figGrind,fullfile(outDir, ...
    'D20_return_gap_required_centre_grind_for_2p3mH.fig'));

figMu = figure('Color','w','Position',[160 160 980 620]);
axMu = axes(figMu); hold(axMu,'on'); grid(axMu,'on'); box(axMu,'on');
fill(axMu,[gGlue_um;flipud(gGlue_um)],[LmMuLow_H;flipud(LmMuHigh_H)]*1e3, ...
    [0.04 0.32 0.75],'FaceAlpha',0.16,'EdgeColor','none', ...
    'DisplayName',sprintf('研磨0.10 mm/片：\\mu \\pm%g%%带宽',muTolerance_pct));
fill(axMu,[gGlue_um;flipud(gGlue_um)],[LmMuLow07_H;flipud(LmMuHigh07_H)]*1e3, ...
    [0.86 0.24 0.08],'FaceAlpha',0.16,'EdgeColor','none', ...
    'DisplayName',sprintf('研磨0.07 mm/片：\\mu \\pm%g%%带宽',muTolerance_pct));
plot(axMu,gGlue_um,LmMuNom_H*1e3,'LineWidth',2.4,'Color',[0.04 0.32 0.75], ...
    'DisplayName','研磨0.10 mm/片：\mu标称');
plot(axMu,gGlue_um,LmMuNom07_H*1e3,'LineWidth',2.4,'Color',[0.86 0.24 0.08], ...
    'DisplayName','研磨0.07 mm/片：\mu标称');
yline(axMu,LmTarget_H*1e3,'--','目标2.3 mH','LineWidth',1.5, ...
    'LabelHorizontalAlignment','left','HandleVisibility','off');
xlabel(axMu,'Cured adhesive thickness between return-leg faces (um)');
ylabel(axMu,'Magnetizing inductance L_m (mH)');
title(axMu,{sprintf('D20/Core43，N_p=36：铁氧体磁导率\\pm%g%%对L_m的影响',muTolerance_pct), ...
    sprintf('气隙主导磁路，标称点磁芯磁阻占比仅%.1f%%',100*coreFractionNominal(1))}, ...
    'FontName','Microsoft YaHei');
subtitle(axMu,sprintf(['未开气隙时L_m将在%.2f~%.2f mH之间（\\pm%g%%全量传递），' ...
    '开气隙后带宽压缩到%+.2f%%/%+.2f%%'],LmUngappedMu_mH(1),LmUngappedMu_mH(3), ...
    muTolerance_pct,deltaMuLow_pct(1),deltaMuHigh_pct(1)),'FontName','Microsoft YaHei');
legend(axMu,'Location','northwest','FontName','Microsoft YaHei');
exportgraphics(figMu,fullfile(outDir, ...
    'D20_mu_tolerance_Lm_sensitivity.png'),'Resolution',240);
savefig(figMu,fullfile(outDir,'D20_mu_tolerance_Lm_sensitivity.fig'));

figBead = figure('Color','w','Position',[190 190 1180 560]);
tlBead = tiledlayout(figBead,1,2,'TileSpacing','compact','Padding','compact');

% Left tile: Lm against bead diameter for the unground build, with the
% permeability band drawn around it.
axB1 = nexttile(tlBead); hold(axB1,'on'); grid(axB1,'on'); box(axB1,'on');
LmBeadLow_H = Np^2./(RcoreMu_AtPerWb(1) + beadDia_m*beadGapCoefficient);
LmBeadHigh_H = Np^2./(RcoreMu_AtPerWb(3) + beadDia_m*beadGapCoefficient);
patch(axB1,[beadWindowFor5pct_um(1) beadWindowFor5pct_um(2) ...
    beadWindowFor5pct_um(2) beadWindowFor5pct_um(1)], ...
    [0.95 0.95 1.05 1.05]*LmTarget_H*1e3,[0.20 0.60 0.30], ...
    'FaceAlpha',0.12,'EdgeColor','none','DisplayName','\pm5% L_m合格窗口');
fill(axB1,[beadDia_um;flipud(beadDia_um)], ...
    [LmBeadLow_H;flipud(LmBeadHigh_H)]*1e3,[0.10 0.35 0.70], ...
    'FaceAlpha',0.18,'EdgeColor','none', ...
    'DisplayName',sprintf('\\mu \\pm%g%%带宽',muTolerance_pct));
plot(axB1,beadDia_um,LmBead_H*1e3,'LineWidth',2.6,'Color',[0.10 0.35 0.70], ...
    'DisplayName','不研磨，珠子控制均匀气隙');
yline(axB1,LmTarget_H*1e3,'--','目标2.3 mH','LineWidth',1.5, ...
    'LabelHorizontalAlignment','right','LabelVerticalAlignment','bottom', ...
    'HandleVisibility','off');
plot(axB1,beadForTarget_m*1e6,LmTarget_H*1e3,'o','MarkerSize',9, ...
    'LineWidth',2,'Color',[0.10 0.55 0.25],'MarkerFaceColor','w', ...
    'DisplayName',sprintf('%.1f um：正中目标',beadForTarget_m*1e6));
plot(axB1,100,Lm100umBead_H*1e3,'s','MarkerSize',10,'LineWidth',2, ...
    'Color',[0.80 0.15 0.10],'MarkerFaceColor','w', ...
    'DisplayName',sprintf('100 um珠：%.3f mH (%+.1f%%)', ...
    Lm100umBead_H*1e3,delta100umBead_pct));
xlabel(axB1,'Glass bead diameter, no centre grinding (um)');
ylabel(axB1,'Magnetizing inductance L_m (mH)');
title(axB1,'不研磨：珠径决定L_m','FontName','Microsoft YaHei');
subtitle(axB1,sprintf('合格窗口仅%.1f~%.1f um（\\pm%.1f um）', ...
    beadWindowFor5pct_um(1),beadWindowFor5pct_um(2), ...
    diff(beadWindowFor5pct_um)/2),'FontName','Microsoft YaHei');
legend(axB1,'Location','northeast','FontName','Microsoft YaHei');
xlim(axB1,[60 130]);

% Right tile: both processes referred to the same horizontal axis, the
% thickness error away from whatever value puts that process on target.
axB2 = nexttile(tlBead); hold(axB2,'on'); grid(axB2,'on'); box(axB2,'on');
dev_um = (-15:0.25:15)';
dev_m = dev_um*1e-6;
LmDevBead_H = Np^2./(Rcore_AtPerWb + (beadForTarget_m+dev_m)*beadGapCoefficient);
LmDevGrind_H = Np^2./(Rcore_AtPerWb + ...
    (centreOnlyEquivalentGap_m+dev_m)/(mu0*Ac_m2));
yline(axB2,5,':','+5%','LineWidth',1.2,'LabelHorizontalAlignment','left', ...
    'HandleVisibility','off');
yline(axB2,-5,':','-5%','LineWidth',1.2,'LabelHorizontalAlignment','left', ...
    'HandleVisibility','off');
plot(axB2,dev_um,100*(LmDevBead_H/LmTarget_H-1),'LineWidth',2.6, ...
    'Color',[0.10 0.35 0.70],'DisplayName', ...
    sprintf('珠子均匀气隙：%.2f %%/um',sensBead_pctPerUm));
plot(axB2,dev_um,100*(LmDevGrind_H/LmTarget_H-1),'LineWidth',2.6, ...
    'Color',[0.85 0.45 0.05],'DisplayName', ...
    sprintf('仅中柱研磨：%.2f %%/um',sensGrind_pctPerUm));
xlabel(axB2,'Thickness error from the on-target value (um)');
ylabel(axB2,'L_m deviation from 2.3 mH (%)');
title(axB2,'同样1 um误差，两种工艺的代价','FontName','Microsoft YaHei');
subtitle(axB2,sprintf(['珠子气隙在回路中出现两次且外柱截面更小，敏感度是研磨的%.2f倍'], ...
    sensRatio),'FontName','Microsoft YaHei');
legend(axB2,'Location','northeast','FontName','Microsoft YaHei');
exportgraphics(figBead,fullfile(outDir, ...
    'D20_no_grind_bead_controlled_gap.png'),'Resolution',240);
savefig(figBead,fullfile(outDir,'D20_no_grind_bead_controlled_gap.fig'));

sample_um = [0 2 5 10 20 30 40 50 75 100]';
Sample = Result(ismember(Result.ReturnGlueGap_um,sample_um),:);
Sample07 = Result07(ismember(Result07.ReturnGlueGap_um,sample_um),:);
writetable(Sample,fullfile(outDir,'D20_0p1mm_each_core_glue_gap_Lm_selected.csv'));
writetable(Sample07,fullfile(outDir,'D20_0p07mm_each_core_glue_gap_Lm_selected.csv'));

Design = struct('Np',Np,'LmTarget_mH',LmTarget_H*1e3, ...
    'CentreArea_mm2',Ac_m2*1e6,'TotalReturnArea_mm2',Ar_m2*1e6, ...
    'AreaRatio_Ac_over_Ar',areaRatio,'GrindEachCore_mm',grindEachCore_mm, ...
    'TotalCentreGrind_mm',dTotal_m*1e3, ...
    'ReferenceUniformSplitGap_mm',gUniformRef_m*1e3, ...
    'TargetAL_nH_per_turn2',LmTarget_H/Np^2*1e9, ...
    'ReturnFaceGlueForTarget_um',gGlueForTarget_m*1e6, ...
    'AllowableReturnGlueFor5pct_um',[allowableGlueMin_m allowableGlueMax_m]*1e6, ...
    'GrindEachCore07_mm',grindEachCore07_mm, ...
    'TotalCentreGrind07_mm',dTotal07_m*1e3, ...
    'ReturnFaceGlueForTarget07_um',gGlueForTarget07_m*1e6, ...
    'AllowableReturnGlueFor5pct07_um',[allowableGlue07Min_m allowableGlue07Max_m]*1e6, ...
    'CentreOnlyEquivalentGap_mm',centreOnlyEquivalentGap_m*1e3, ...
    'ReturnGapForZeroGrind_um',returnGapForZeroGrind_m*1e6, ...
    'ExternalSideFilletCreatesMagneticGap',false, ...
    'CoreReluctance_AtPerWb',Rcore_AtPerWb, ...
    'PermeabilityTolerance_pct',muTolerance_pct, ...
    'CoreReluctanceShareAtNoGlue_pct',100*coreFractionNominal(1), ...
    'CoreReluctanceShareAtNoGlue07_pct',100*coreFractionNominal07(1), ...
    'LmAtMuCornersNoGlue_mH',[LmMuLow_H(1) LmMuNom_H(1) LmMuHigh_H(1)]*1e3, ...
    'LmDeltaAtMuCornersNoGlue_pct',[deltaMuLow_pct(1) deltaMuHigh_pct(1)], ...
    'LmDeltaAtMuCornersNoGlue07_pct',[deltaMuLow07_pct(1) deltaMuHigh07_pct(1)], ...
    'LmUngappedAtMuCorners_mH',LmUngappedMu_mH, ...
    'GrindTolerance_mm',grindTolerance_mm, ...
    'CombinedCornerSpread_pct',[cornerSpreadLow_pct cornerSpreadHigh_pct]);
save(fullfile(outDir,'D20_0p1mm_each_core_glue_gap_Lm_sweep.mat'), ...
    'Design','Result','Result07','Sample','Sample07','ProductionCases', ...
    'ProductionCases07','RequiredGrind','RequiredGrindSelected', ...
    'MuSensitivity','MuSensitivity07','MuSensitivitySelected', ...
    'MuSensitivitySelected07','CornerCases','BeadSweep', ...
    'GrindFamilySummary','GrindFamilyLm');

reportPath = fullfile(outDir,'D20_0p1mm_each_core_glue_gap_Lm_report.txt');
fid = fopen(reportPath,'w');
fprintf(fid,'D20/Core43, Np=36, target Lm=2.3 mH\n');
fprintf(fid,'Centre-post grinding: 0.1 mm on each core half, 0.2 mm total\n');
fprintf(fid,'Ac=%.6f mm^2, total return area=%.6f mm^2\n',Ac_m2*1e6,Ar_m2*1e6);
fprintf(fid,'Glue trapped between return faces also opens the centre gap.\n');
fprintf(fid,'Actual centre gap = 0.2 mm + return glue gap.\n');
fprintf(fid,'Centre-referred gap = 0.2 mm + (1 + Ac/Ar)*return glue gap.\n');
fprintf(fid,'Ac/Ar = %.9f; return glue multiplier = %.9f.\n',areaRatio,1+areaRatio);
fprintf(fid,'Glue gap for exactly 2.3 mH in this estimate: %.6f um\n',gGlueForTarget_m*1e6);
fprintf(fid,'Return-face glue range satisfying +/-5%% Lm: %.6f to %.6f um\n', ...
    allowableGlueMin_m*1e6,allowableGlueMax_m*1e6);
fprintf(fid,'\nSecond group: centre-post grinding 0.07 mm on each half, 0.14 mm total\n');
fprintf(fid,'Glue gap for exactly 2.3 mH: %.6f um\n',gGlueForTarget07_m*1e6);
fprintf(fid,'Return-face glue range satisfying +/-5%% Lm: %.6f to %.6f um\n', ...
    allowableGlue07Min_m*1e6,allowableGlue07Max_m*1e6);
fprintf(fid,'An external side fillet does not enter the magnetic circuit: use glue gap = 0.\n\n');
fprintf(fid,'Return glue (um) | Actual centre gap (mm) | Equivalent gap (mm) | Lm (mH) | Delta (%%)\n');
for k=1:height(Sample)
    fprintf(fid,'%16.1f | %22.6f | %19.6f | %7.4f | %+9.3f\n', ...
        Sample.ReturnGlueGap_um(k),Sample.ActualCentreGap_mm(k), ...
        Sample.CentreReferredEquivalentGap_mm(k),Sample.Lm_mH(k), ...
        Sample.DeltaFrom2p3mH_pct(k));
end
fprintf(fid,'\nProduction cases:\n');
for k=1:height(ProductionCases)
    fprintf(fid,'%s: magnetic return gap %.3f um, centre gap %.6f mm, Lm %.4f mH (%+.3f%%)\n', ...
        ProductionCases.Scenario(k),ProductionCases.MagneticReturnGap_um(k), ...
        ProductionCases.ActualCentreGap_mm(k),ProductionCases.Lm_mH(k), ...
        ProductionCases.DeltaFrom2p3mH_pct(k));
end
fprintf(fid,'\nManufacturing conclusion:\n');
fprintf(fid,'Keep adhesive off the horizontal return-leg mating faces.\n');
fprintf(fid,'Use an external side fillet while the lapped return faces are clamped in contact.\n');
fprintf(fid,'With 0.1 mm ground from each centre half, 90-100 um beads between return faces are unsuitable.\n');
fprintf(fid,'\n0.07 mm/core production cases:\n');
for k=1:height(ProductionCases07)
    fprintf(fid,'%s: return gap %.3f um, centre gap %.6f mm, Lm %.4f mH (%+.3f%%)\n', ...
        ProductionCases07.Scenario(k),ProductionCases07.MagneticReturnGap_um(k), ...
        ProductionCases07.ActualCentreGap_mm(k),ProductionCases07.Lm_mH(k), ...
        ProductionCases07.DeltaFrom2p3mH_pct(k));
end
fprintf(fid,'\nRequired centre grind for target Lm versus residual return gap:\n');
fprintf(fid,'Return gap (um) | Total centre grind (mm) | Grind each core (mm) | Assembled centre gap (mm)\n');
for k=1:height(RequiredGrindSelected)
    fprintf(fid,'%15.1f | %23.6f | %20.6f | %25.6f\n', ...
        RequiredGrindSelected.ReturnLegResidualGap_um(k), ...
        RequiredGrindSelected.RequiredTotalCentreGrind_mm(k), ...
        RequiredGrindSelected.RequiredGrindPerCore_mm(k), ...
        RequiredGrindSelected.AssembledCentreGap_mm(k));
end
fprintf(fid,'Zero centre grind occurs at a uniform split gap of %.6f um.\n', ...
    returnGapForZeroGrind_m*1e6);

fprintf(fid,'\nFerrite permeability tolerance +/-%.0f%%:\n',muTolerance_pct);
fprintf(fid,'Inferred core reluctance at nominal mu: %.1f At/Wb.\n',Rcore_AtPerWb);
fprintf(fid,'Ungapped core would give Lm = %.3f / %.3f / %.3f mH at mu -%g%% / nominal / +%g%%.\n', ...
    LmUngappedMu_mH(1),LmUngappedMu_mH(2),LmUngappedMu_mH(3), ...
    muTolerance_pct,muTolerance_pct);
fprintf(fid,'With 0.2 mm total centre grind and no glue gap the ferrite holds only\n');
fprintf(fid,'%.2f%% of the total reluctance, so Lm moves %+.3f%% / %+.3f%% at mu -%g%% / +%g%%.\n', ...
    100*coreFractionNominal(1),deltaMuLow_pct(1),deltaMuHigh_pct(1), ...
    muTolerance_pct,muTolerance_pct);
fprintf(fid,'With 0.14 mm total centre grind the ferrite share is %.2f%% and Lm moves %+.3f%% / %+.3f%%.\n', ...
    100*coreFractionNominal07(1),deltaMuLow07_pct(1),deltaMuHigh07_pct(1));
fprintf(fid,['Return glue (um) | Core share (%%) | Lm mu-%g%% | Lm nom | ' ...
    'Lm mu+%g%% | band (%%)\n'],muTolerance_pct,muTolerance_pct);
muRows = MuSensitivitySelected{:,:};
for k=1:size(muRows,1)
    fprintf(fid,'%16.1f | %14.2f | %9.4f | %6.4f | %9.4f | %8.3f\n', ...
        muRows(k,1),muRows(k,2),muRows(k,3),muRows(k,4),muRows(k,5),muRows(k,8));
end
fprintf(fid,'\nCombined worst case at glue gap 0, mu +/-%.0f%% with centre grind +/-%.3f mm:\n', ...
    muTolerance_pct,grindTolerance_mm);
fprintf(fid,'Lm spans %.4f to %.4f mH (%+.2f%% to %+.2f%% of the %.4f mH nominal).\n', ...
    LmCornerMin_mH,LmCornerMax_mH,cornerSpreadLow_pct,cornerSpreadHigh_pct, ...
    LmNominalNoGlue_mH);
fprintf(fid,'The grind tolerance dominates; permeability spread is the smaller term.\n');

fprintf(fid,'\nGrind-depth family, glue gap between return faces vs Lm:\n');
fprintf(fid,['Grind/core (mm) | Total (mm) | Lm no glue (mH) | Delta (%%) | ' ...
    'Glue for 2.3 mH (um) | +/-5%% glue window (um)\n']);
for j = 1:nGrind
    if targetReachable(j)
        targetText = sprintf('%20.2f',glueTargetFamily_m(j)*1e6);
    else
        targetText = sprintf('%20s','unreachable');
    end
    if windowExists(j)
        windowText = sprintf('%.2f to %.2f',glueMinFamily_m(j)*1e6, ...
            glueMaxFamily_m(j)*1e6);
    else
        windowText = 'none';
    end
    fprintf(fid,'%15.2f | %10.2f | %15.4f | %+9.2f | %s | %s\n', ...
        grindFamily_mm(j),dTotalFamily_m(j)*1e3,LmNoGlueFamily_H(j)*1e3, ...
        100*(LmNoGlueFamily_H(j)/LmTarget_H-1),targetText,windowText);
end
fprintf(fid,'\nLm with %g um cured glue between the return faces:\n',glueCheck_um);
for j = 1:nGrind
    fprintf(fid,'Grind %.2f mm/core: Lm %.4f mH (%+.2f%%)\n', ...
        grindFamily_mm(j),LmGlueCheckFamily_H(j)*1e3,deltaGlueCheckFamily_pct(j));
end
fclose(fid);

fprintf('Total centre grind: %.3f mm (%.3f mm on each half)\n', ...
    dTotal_m*1e3,grindEachCore_mm);
fprintf('Return-face glue gap for Lm=2.3 mH: %.3f um\n',gGlueForTarget_m*1e6);
fprintf('+/-5%% Lm return-face glue range: %.3f to %.3f um\n', ...
    allowableGlueMin_m*1e6,allowableGlueMax_m*1e6);
fprintf('0.07 mm/core target return-face glue gap: %.3f um\n', ...
    gGlueForTarget07_m*1e6);
fprintf('0.07 mm/core +/-5%% glue range: %.3f to %.3f um\n', ...
    allowableGlue07Min_m*1e6,allowableGlue07Max_m*1e6);
disp(Sample);
disp(Sample07);
fprintf('\n--- Grind-depth family (glue gap vs Lm) ---\n');
disp(GrindFamilySummary);
disp(GrindFamilyLm(ismember(GrindFamilyLm.ReturnGlueGap_um,sample_um),:));
disp(ProductionCases);
disp(ProductionCases07);
disp(RequiredGrindSelected);

fprintf('\n--- Permeability tolerance +/-%.0f%% ---\n',muTolerance_pct);
fprintf('Core reluctance at nominal mu: %.1f At/Wb\n',Rcore_AtPerWb);
fprintf('Ungapped Lm at mu -%g%%/nom/+%g%%: %.3f / %.3f / %.3f mH\n', ...
    muTolerance_pct,muTolerance_pct, ...
    LmUngappedMu_mH(1),LmUngappedMu_mH(2),LmUngappedMu_mH(3));
fprintf('0.10 mm/core, no glue gap: core share %.2f%%, Lm %+.3f%% / %+.3f%%\n', ...
    100*coreFractionNominal(1),deltaMuLow_pct(1),deltaMuHigh_pct(1));
fprintf('0.07 mm/core, no glue gap: core share %.2f%%, Lm %+.3f%% / %+.3f%%\n', ...
    100*coreFractionNominal07(1),deltaMuLow07_pct(1),deltaMuHigh07_pct(1));
fprintf('Combined mu +/-%g%% and grind +/-%.3f mm: Lm %.4f to %.4f mH (%+.2f%% to %+.2f%%)\n', ...
    muTolerance_pct,grindTolerance_mm,LmCornerMin_mH,LmCornerMax_mH, ...
    cornerSpreadLow_pct,cornerSpreadHigh_pct);
disp(MuSensitivitySelected);
disp(MuSensitivitySelected07);
disp(CornerCases);

fprintf('\n--- No grinding, bead-controlled uniform gap ---\n');
fprintf('Bead diameter for exactly 2.3 mH: %.3f um\n',beadForTarget_m*1e6);
fprintf('Bead window for +/-5%% Lm: %.3f to %.3f um (+/-%.3f um)\n', ...
    beadWindowFor5pct_um(1),beadWindowFor5pct_um(2), ...
    diff(beadWindowFor5pct_um)/2);
fprintf('Nominal 0.1 mm beads: Lm = %.4f mH (%+.2f%%); Np=%.1f would recentre it\n', ...
    Lm100umBead_H*1e3,delta100umBead_pct,NpFor100umBead);
fprintf('Sensitivity: bead %.4f %%/um vs centre grind %.4f %%/um (ratio %.2fx)\n', ...
    sensBead_pctPerUm,sensGrind_pctPerUm,sensRatio);
fprintf('Bead build at mu -%g%%/nom/+%g%%: %.4f / %.4f / %.4f mH (%+.3f%% / %+.3f%%)\n', ...
    muTolerance_pct,muTolerance_pct,LmBeadMu_mH(1),LmBeadMu_mH(2), ...
    LmBeadMu_mH(3),deltaBeadMu_pct(1),deltaBeadMu_pct(3));
disp(BeadSweep(ismember(BeadSweep.BeadDiameter_um, ...
    [60 70 80 85 90 93 95 100 105 110 120 130]'),:));
fprintf('Results: %s\n',outDir);
